package de.vogella.itext.write;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.ArrayList;

import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfWriter;

public class FirstPdf2 {
	public ArrayList a = new ArrayList();

	public static void main(String[] args) {
		FirstPdf2 fpdf = new FirstPdf2();
		String path = "D:\\MC\\title.pdf";
		// String path="D:\\Downloads\\Minhchung_PhanI_TC1_TC11(23-Oct-2018)\\";
		// File folder = new File(path);
		// File[] listOfFiles = folder.listFiles();
		fpdf.init();
		Document document = new Document();
		try {
			PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(path));
			document.open();
			for (int i = 0; i < fpdf.a.size() / 2; i++) {
				String title = "" + fpdf.a.get((i * 2));
				String content = "" + fpdf.a.get((i * 2) + 1);
				System.out.println(title);
				System.out.println(content);
				// if (listOfFiles[i].isFile()) {
				// String fname1=listOfFiles[i].getName();

				// if(fname1.toLowerCase().contains(" - marker.pdf")) {
				// listOfFiles[i].delete();
				// }
				// if(!fname1.toLowerCase().contains(" - marker.pdf")) {
				// String fname=fname1.replace(".pdf", " - marker.pdf");
				// System.out.println("File " + fname);
				// BaseFont courier = BaseFont.createFont(BaseFont.COURIER, BaseFont.UT,
				// BaseFont.EMBEDDED);
				BaseFont bf = BaseFont.createFont("c:\\windows\\fonts\\times.ttf", BaseFont.IDENTITY_H,
						BaseFont.EMBEDDED);
				// Font font =FontFactory.getFont("sanskrit", "Identity-H", true);
				// Chunk chunk = new Chunk(fname1,font);
				// document.add(new Paragraph(chunk));
				Paragraph p0 = new Paragraph("\n\n\n", new Font(bf, 28, Font.BOLD));
				document.add(p0);
				Paragraph p1 = new Paragraph(title, new Font(bf, 28, Font.BOLD));
				p1.setAlignment(Element.ALIGN_CENTER);
				document.add(p1);
				Paragraph p2 = new Paragraph(content, new Font(bf, 22));
				p2.setAlignment(Element.ALIGN_CENTER);
				document.add(p2);
				document.newPage();
				// }else {
				// System.out.println("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
				// }
				// }

			}
			document.close();
			writer.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void init() {
		a.add("Exh.Intro-01");
		a.add("Quyết định 1086/QĐ-ĐHCT ngày 17/4/2014 về ban hành Quy định hoạt động đảm bảo chất lượng \n của Trường ĐHCT");
		a.add("Exh.Intro-02");
		a.add("Quyết định 626/QĐ-ĐHCT ngày 25/4/2007 về thành lập Bộ môn Công nghệ phần mềm và điều động cán bộ");
		a.add("Exh.Intro-03");
		a.add("Quyết định 475/QĐ-CNTT ngày 03/06/2018 về thành lập Tổ kiểm định chất lượng CTĐT Kỹ sư KTPM");
		a.add("Exh.Intro-04");
		a.add("Quyết định 532/QĐ-ĐHCT ngày 16/04/2010 \nvề việc thành lập các Tổ tự đánh giá CTĐT theo chuẩn AUN");
		a.add("Exh.Intro-05");
		a.add("Quyết định 572/QĐ-ĐHCT ngày 12/03/2015 \nvề việc thực hiện đánh giá thử CTĐT ngành KTPM \ntheo chuẩn ABET");
		a.add("Exh.Intro-06");
		a.add("Quyết định 2473/QĐ-ĐHCT ngày 26/06/2018 \nvề việc thành lập các Tổ tự đánh giá CTĐT năm 2018");
		a.add("Exh.1.1-01");
		a.add("Mô tả chương trình; mục tiêu đào tạo, \nchuẩn đầu ra và chương trình đào tạo; \nma trận tương quan; kế hoạch học tập mẫu");
		a.add("Exh.1.1-02");
		a.add("Quyết định thành lập hội đồng khoa học và đào tạo \nKhoa CNTT&TT");
		a.add("Exh.1.1-03");
		a.add("Quyết định thành lập Ban chỉ đạo, tổ thư ký, tổ điều chỉnh chương trình KTPM");
		a.add("Exh.1.1-04");
		a.add("Đề xuất chương trình đào tạo KTPM theo ACM");
		a.add("Exh.1.1-05");
		a.add("Các biên bản họp cải tiến chương trình KTPM");
		a.add("Exh.1.1-06");
		a.add("Kết quả lấy ý kiến của sinh viên tốt nghiệp \nđối với chương trình đào tạo");
		a.add("Exh.1.1-07");
		a.add("Các tài liệu tham khảo");
		a.add("Exh.1.1-08");
		a.add("Trang web giới thiệu chuẩn đầu ra các ngành \nvà chuyên ngành đào tạo \nhttps://www.ctu.edu.vn/chuan-dau-ra-ncs.html?id=502");
		a.add("Exh.1.3-01");
		a.add("Thông tư 07/2015/TT-BGDĐT");
		a.add("Exh.1.3-02");
		a.add("Phản hồi từ phía người sử dụng lao động");
		a.add("Exh.2.1-01");
		a.add("Trang web \nhttp://http://www.cit.ctu.edu.vn/index.php/dao-t-o/chuong-trinh-d-i-h-c");
		a.add("Exh.2.1-02");
		a.add("Trang web https://tuyensinh.ctu.edu.vn");
		a.add("Exh.2.1-03");
		a.add("Poster quảng bá, tờ rơi để giới thiệu các CTĐT \ncủa Khoa CNTT&TT");
		a.add("Exh.2.1-04");
		a.add("Nhóm minh chứng cho việc cải tiến CTĐT");
		a.add("Exh.2.2-01");
		a.add("Nhóm minh chứng cho việc quản lý, \ncông bố kế hoạch giảng dạy học phần");
		a.add("Exh.2.2-02");
		a.add("Nhóm minh chứng cho việc quản lý, \ncải tiến đề cương học phần");
		a.add("Exh.4.1-01");
		a.add("Quy chế 43");
		a.add("Exh.4.1-02");
		a.add("Thông tư ban hành quy định \nvề kiểm định chất lượng cơ sở giáo dục đại học \n12/2017");
		a.add("Exh.4.1-03");
		a.add("Kế hoạch phát triển 2012-2017");
		a.add("Exh.4.1-04");
		a.add("Báo cáo tổng kết năm học 2013-2014 \nvà kế hoạch công tác 2014-2015");
		a.add("Exh.4.1-05");
		a.add("Chương trình đào tạo ngành KTPM K40");
		a.add("Exh.4.1-06");
		a.add("Thông báo mở lại hệ thống nhập kế hoạch học tập");
		a.add("Exh.4.1-07");
		a.add("Kế hoạch học tập mẫu ngành KTPM");
		a.add("Exh.4.1-08");
		a.add("Đề cương thực tập thực tế (CT454)");
		a.add("Exh.4.1-09");
		a.add("Trang web ĐHCT công bố CTĐT ngành KTPM https://www.ctu.edu.vn/dao-tao/ctdt-dai-hoc.html");
		a.add("Exh.4.1-10");
		a.add("Kế hoạch sinh hoạt đầu khóa cho sinh viên mới");
		a.add("Exh.4.1-11");
		a.add("Slide sinh hoạt đầu khóa cho sinh viên mới");
		a.add("Exh.4.1-12");
		a.add("Thông báo sinh hoạt đầu năm học cho sinh viên khóa cũ");
		a.add("Exh.4.1-13");
		a.add("Slide sinh hoạt đầu năm học cho sinh viên khóa cũ");
		a.add("Exh.4.1-14");
		a.add("Quyết định số 2742/QĐ-ĐHCT ngày 15-08-2017 \nvề việc ban hành Quy định \nvề Công tác học vụ");
		a.add("Exh.4.1-15");
		a.add("Thông báo mở lớp bồi dưỡng Nghiệp vụ Sư phạm \nnăm 2016");
		a.add("Exh.4.1-16");
		a.add("Danh sách giảng viên tham dự \nlớp bồi dưỡng Nghiệp vụ Sư phạm 2016");
		a.add("Exh.4.2-01");
		a.add("Đề cương chi tiết \nhọc phần Nhập môn Công nghệ phần mềm (CT171)");
		a.add("Exh.4.2-02");
		a.add("Đề cương chi tiết \nhọc phần Lập trình căn bản (CT101)");
		a.add("Exh.4.2-03");
		a.add("Website Hệ thống hỗ trợ học tập \ncủa Khoa CNTT&TT https://elcit.ctu.edu.vn/");
		a.add("Exh.4.2-04");
		a.add("Đề cương chi tiết \nhọc phần Bảo trì phần mềm (CT244)");
		a.add("Exh.4.2-05");
		a.add("Đề cương chi tiết \nhọc phần Niên luận cơ sở ngành KTPM (CT239)");
		a.add("Exh.4.2-06");
		a.add("Danh sách đề tài \nniên luận cơ sở ngành KTPM (CT239)");
		a.add("Exh.4.2-07");
		a.add("Đề cương chi tiết \nhọc phần Niên luận ngành KTPM (CT250)");
		a.add("Exh.4.2-08");
		a.add("Phiếu đánh giá kỹ năng làm việc nhóm niên luận ngành KTPM");
		a.add("Exh.4.2-09");
		a.add("Phiếu đánh giá kỹ năng thuyết trình nhóm niên luận ngành KTPM");
		a.add("Exh.4.2-10");
		a.add("Danh sách phân nhóm đề tài niên luận ngành KTPM");
		a.add("Exh.4.2-11");
		a.add("Thông báo và danh sách đề tài luận văn tốt nghiệp");
		a.add("Exh.4.2-12");
		a.add("Qui định và đề cương thực tập thực tế");
		a.add("Exh.4.2-13");
		a.add("Danh sách phân công \ngiảng viên hướng dẫn sinh viên thực tập thực tế");
		a.add("Exh.4.2-14");
		a.add("Nội dung công tác đi thăm sinh viên thực tập");
		a.add("Exh.4.2-15");
		a.add("Thông báo \ntuyển sinh viên thực tập thực tế \ncủa doanh nghiệp");
		a.add("Exh.4.2-16");
		a.add("Đề cương chi tiết \nhọc phần Phân tích thiết kế thuật toán (CT174)");
		a.add("Exh.4.2-17");
		a.add("Phiếu đánh giá điểm rèn luyện của sinh viên");
		a.add("Exh.4.2-18");
		a.add("Hướng dẫn thực hiện \nvà quản lý đề tài NCKH của sinh viên");
		a.add("Exh.4.2-19");
		a.add("Quyết định phê duyệt danh mục đề tài NCKH \ncủa sinh viên năm 2018");
		a.add("Exh.4.2-20");
		a.add("Website \nHệ thống khảo sát học phần trực tuyến của ĐHCT \nhttps://oss.ctu.edu.vn/");
		a.add("Exh.4.2-21");
		a.add("Các mẫu phiếu khảo sát trực tuyến dành cho sinh viên");
		a.add("Exh.4.2-22");
		a.add("Kết quả khảo sát của học phần");
		a.add("Exh.4.2-23");
		a.add("Biên bản họp với các doanh nghiệp 12/2017");
		a.add("Exh.4.3-01");
		a.add("Đề cương chi tiết \nLuận văn tốt nghiệp ngành KTPM (CT594)");
		a.add("Exh.4.3-02");
		a.add("Thông báo \nvề việc thực hiện Luận văn tốt nghiệp của Bộ môn CNPM \nHọc kỳ 2 2016-2017");
		a.add("Exh.4.3-03");
		a.add("Hướng dẫn về việc xét miễn và công nhận điểm học phần");
		a.add("Exh.4.3-04");
		a.add("Quy chế về việc cử sinh viên đi học tập ở nước ngoài");
		a.add("Exh.4.3-05");
		a.add("Quyết định cho phép sinh viên đi học tập ở nước ngoài");
		a.add("Exh.5.1-01");
		a.add("Quy chế \nTuyển sinh đại học, cao đẳng hệ chính quy \nban hành kèm theo Thông tư số 03/2015/TT-BGDĐT");
		a.add("Exh.5.1-02");
		a.add("Thông tin tuyển sinh năm 2012 của Trường ĐHCT");
		a.add("Exh.5.1-03");
		a.add("Thông tin tuyển sinh năm 2013 của Trường ĐHCT");
		a.add("Exh.5.1-04");
		a.add("Đề cương chi tiết \nhọc phần Nhập môn Công nghệ phần mềm (CT171)");
		a.add("Exh.5.1-05");
		a.add("Phiếu đánh giá báo cáo kết quả thực tập thực tế");
		a.add("Exh.5.1-06");
		a.add("Quy định \nvề việc thực hiện và đánh giá luận văn tốt nghiệp đại học");
		a.add("Exh.5.1-07");
		a.add("Quyết định thành lập \nHội đồng chấm Luận văn tốt nghiệp  đại học học kỳ 2 2017-2018");
		a.add("Exh.5.1-08");
		a.add("Phiếu chấm luận văn dành cho thành viên Hội đồng chấm");
		a.add("Exh.5.1-09");
		a.add("Mẫu biên bản \ncủa Hội đồng chấm điểm Luận văn tốt nghiệp");
		a.add("Exh.5.2-01");
		a.add("Kế hoạch khung công tác năm 2018 của Trường ĐHCT");
		a.add("Exh.5.2-02");
		a.add("Kế hoạch giảng dạy học phần CT174");
		a.add("Exh.5.2-03");
		a.add("Mẫu đáp án đề thi cuối kỳ học phần CT174");
		a.add("Exh.5.3-01");
		a.add("Mẫu đề thi kiểm tra giữa kỳ học phần CT174");
		a.add("Exh.5.3-02");
		a.add("Mẫu đề thi cuối kỳ phần thực hành học phần CT174");
		a.add("Exh.5.3-03");
		a.add("Mẫu đề thi cuối kỳ phần lý thuyết học phần CT174");
		a.add("Exh.5.3-04");
		a.add("Kết quả kiểm tra giữa kỳ \nhọc phần CT174 được xuất ra tập tin");
		a.add("Exh.5.3-05");
		a.add("Quyết định 73/QĐ-ĐHCT ngày 11-01-2017 \nvề Quy chế đánh giá điểm rèn luyện của sinh viên");
		a.add("Exh.5.3-06");
		a.add("Quyết định 939-QĐ-ĐHCT ngày 28-03-2017 \nban hành Quy chế chi tiêu nội bộ Trường ĐHCT");
		a.add("Exh.5.3-07");
		a.add("Biên bản họp Bộ môn \nđiều chỉnh Đề cương học phần CT240");
		a.add("Exh.5.3-08");
		a.add("Đề cương chi tiết \nhọc phần Nguyên lý xây dựng phần mềm khóa 43");
		a.add("Exh.5.3-09");
		a.add("Đề cương chi tiết \nhọc phần Nguyên lý xây dựng phần mềm  khóa 44");
		a.add("Exh.5.3-10");
		a.add("Mẫu quy định hình thức viết báo cáo \nLuận văn tốt nghiệp đại học ngành KTPM");
		a.add("Exh.5.3-11");
		a.add("Phiếu lấy ý kiến của nhà sử dụng lao động \nvề chương trình đào tạo");
		a.add("Exh.5.3-12");
		a.add("Phiếu lấy ý kiến của cựu sinh viên về chương trình đào tạo");
		a.add("Exh.5.4-01");
		a.add("Đề cương chi tiết \nhọc phần Phát triển phần mềm tác nghiệp CT249");
		a.add("Exh.5.4-02");
		a.add("Danh sách điểm danh sinh viên học thực hành");
		a.add("Exh.5.4-03");
		a.add("Bài báo cáo kết quả bài tập thực hành nhóm của sinh viên");
		a.add("Exh.5.4-04");
		a.add("Bảng nhận xét báo cáo thuyết trình nhóm cúa sinh viên");
		a.add("Exh.5.4-05");
		a.add("Bảng điểm thi cuối kỳ \nvà lịch hẹn trao đổi thắc mắc về kết quả");
		a.add("Exh.5.4-06");
		a.add("Phiếu nhận xét, đánh giá luận văn tốt nghiệp");
		a.add("Exh.6.1-01");
		a.add("Kế hoạch phát triển của Khoa CNTT&TT \ngiai đoạn 2012-2017");
		a.add("Exh.6.1-02");
		a.add("Quy định về tiến trình phấn đấu của giảng viên");
		a.add("Exh.6.1-03");
		a.add("Quy hoạch tiến trình phấn đấu giảng viên \nKhoa CNTT&TT");
		a.add("Exh.6.1-04");
		a.add("Thông báo của Trường về kế hoạch đăng ký tuyển dụng");
		a.add("Exh.6.2-01");
		a.add("Qui chế quản lý nhiệm vụ chuyên môn");
		a.add("Exh.6.3-01");
		a.add("Qui định tuyển dụng của Đại học Cần Thơ");
		a.add("Exh.6.3-02");
		a.add("Qui chế bổ nhiệm của Đại học Cần Thơ");
		a.add("Exh.6.3-03");
		a.add("Thông báo tuyển giảng viên Khoa CNTT&TT");
		a.add("Exh.6.3-04");
		a.add("Quyết định kéo dài thời gian làm việc \ncủa thầy Lê Quyết Thắng");
		a.add("Exh.6.4-01");
		a.add("Thông tư liên tịch số 36/2014/TTLT-BGDĐT-BNV \ncủa Bộ Nội vụ-Bộ Giáo dục và Đào tạo : \nQuy định mã số và tiêu chuẩn chức danh nghề nghiệp viên chức giảng dạy \ntrong các cơ sở giáo dục đại học công lập");
		a.add("Exh.6.4-02");
		a.add("Phiếu đăng ký kế hoạch công tác");
		a.add("Exh.6.4-03");
		a.add("Phiếu đánh giá và phân loại viên chức");
		a.add("Exh.6.4-04");
		a.add("Hướng dẫn xét thi đua khen thưởng cuối năm");
		a.add("Exh.6.4-05");
		a.add("Biên bản họp hội đồng thi đua khen thưởng Khoa");
		a.add("Exh.6.4-06");
		a.add("Biên bản xét tăng lương trước hạn");
		a.add("Exh.6.4-07");
		a.add("Phiếu tổng hợp của một học phần");
		a.add("Exh.6.4-08");
		a.add("Phiếu tổng hợp các học phần của bộ môn");
		a.add("Exh.6.4-09");
		a.add("Phiếu tổng hợp các học phần của Khoa");
		a.add("Exh.6.5-01");
		a.add("Minh chứng về đào tạo ngoại ngữ nguồn");
		a.add("Exh.6.5-02");
		a.add("Quyết định cho phép tham dự học bổng");
		a.add("Exh.6.5-03");
		a.add("Quyết định hỗ trợ kinh phí tham dự hội nghị quốc tế");
		a.add("Exh.6.5-04");
		a.add("Danh sách seminar của  bộ môn");
		a.add("Exh.6.5-05");
		a.add("Chứng chỉ tham gia hội thảo");
		a.add("Exh.6.5-06");
		a.add("Danh sách cán bộ đào tạo ABET");
		a.add("Exh.6.6-01");
		a.add("Kế hoạch thực hiện khối lượng công tác chuyên môn \nvà đăng ký thi đua năm học");
		a.add("Exh.6.6-02");
		a.add("Quyết định cho  phép tham dự hội thảo quốc tế \nvới chi phí tư vấn");
		a.add("Exh.6.6-03");
		a.add("Biên bản họp bình bầu thi đua, khen thưởng");
		a.add("Exh.6.7-01");
		a.add("Danh sách chuyên đề được phê duyệt");
		a.add("Exh.6.7-02");
		a.add("Danh sách sách, giáo trình được xuất bản");
		a.add("Exh.6.7-03");
		a.add("Danh sách đề tài NCKH được chấp nhận ở các cấp, \ndự án hợp tác quốc tế");
		a.add("Exh.6.7-04");
		a.add("Trang web http://www.cit.ctu.edu.vn/encict/publication");
		a.add("Exh.7.1-01");
		a.add("Quyết định về chức năng, nhiệm vụ và tổ chức hoạt động \ncủa văn phòng khoa, viện, trung tâm và bộ môn \ntrực thuộc Trường ĐHCT");
		a.add("Exh.7.1-02");
		a.add("Quyết định \nvề việc thành lập các phòng thí nghiệm, phòng thực hành \nvà cử Trưởng phòng thí nghiệm, Trưởng phòng thực hành");
		a.add("Exh.7.1-03");
		a.add("Quyết định cử viên chức phục vụ \nđi học tập nâng cao trình độ từ 2012 – 2017");
		a.add("Exh.7.2-01");
		a.add("Quy định về công tác Phòng thí nghiệm");
		a.add("Exh.7.3-01");
		a.add("Mẫu phiếu đánh giá thi đua");
		a.add("Exh.7.4-01");
		a.add("Kế hoạch đào tạo cán bộ 2017-2019");
		a.add("Exh.7.5-01");
		a.add("Kết quả đánh giá thi đua từ 2012-2017");
		a.add("Exh.8.1.1-01");
		a.add("Quy chế tuyển sinh đại học, cao đẳng hệ chính quy");
		a.add("Exh.8.1.1-02");
		a.add("Thông tư sửa đổi, bổ sung \nquy chế thiTrung học phổ thông");
		a.add("Exh.8.1.1-03");
		a.add("Đề án tuyển sinh đại học chính quy trường ĐHCT 2018");
		a.add("Exh.8.1.1-04");
		a.add("Ngày hội Tư vấn Tuyển sinh - Hướng nghiệp 2017 \ntại Đại học Cần Thơ \nhttps://yu.ctu.edu.vn/index.php/ho-tro-sinh-vien/23-tin-tuc-tong-hop/32-tung-bung-ngay-hoi-tu-van-tuyen-sinh-huong-nghiep-2017-dhct.html");
		a.add("Exh.8.1.1-05");
		a.add("Trang web những điều Tân sinh viên cần biết \nhttps://tansinhvien.ctu.edu.vn");
		a.add("Exh.8.2.1-01 ");
		a.add("Dự thảo báo cáo Tổng kết năm học 2017-2018 \nvà Kế hoạch công tác 2018-2019");
		a.add("Exh.8.3.1-01");
		a.add("Website Hệ thống quản lý \nhttps://htql.ctu.edu.vn/htql/login.php");
		a.add("Exh.8.4.1-01");
		a.add("Bố trí lớp, thời khóa biểu \nvà cố vấn học tập cho tân sinh viên \nhttps://tansinhvien.ctu.edu.vn/hoc-tap/bo-tri-lop-thoi-khoa-bieu-va-co-van-hoc-tap");
		a.add("Exh.8.4.1-02");
		a.add("Quy định Công tác Cố vấn học tập");
		a.add("Exh.8.4.2-01");
		a.add("Cơ cấu tổ chức và các hoạt động \ncủa Đoàn Thanh niên Khoa CNTT&TT");
		a.add("Exh.8.4.3-01");
		a.add("Quyết định khen thưởng sinh viên đạt thành tích \nkỳ thi Olympic Tin học sinh viên");
		a.add("Exh.8.4.4-01");
		a.add("Hình ảnh các hoạt động định hướng nghề nghiệp");
		a.add("Exh.8.5-01");
		a.add("Cảnh quan khu II");
		a.add("Exh.9.1-01");
		a.add("Báo cáo tổng kết nhiệm kỳ 2012-2017 \nvà phương hướng của Khoa CNTT&TT");
		a.add("Exh.9.2-01");
		a.add("Báo cáo tự đánh giá Trường Đại học Cần Thơ 2012-2016");
		a.add("Exh.9.2-02");
		a.add("Website Trung tâm học liệu \nhttp://www.lrc.ctu.edu.vn");
		a.add("Exh.9.2-03");
		a.add("Kế hoạch sinh hoạt đầu năm tại Trung tâm học liệu");
		a.add("Exh.9.2-04");
		a.add("Thống kê sách và tài liệu học tập \ntại Thư viện Khoa CNTT&TT");
		a.add("Exh.9.2-05");
		a.add("Thống kê tần suất sử dụng tài liệu \ntại Thư viện ngành CNTT");
		a.add("Exh.9.3-01");
		a.add("Công khai cơ sở vật chất Trường ĐHCT \nnăm học 2016-2017");
		a.add("Exh.9.3-02");
		a.add("Thống kê phòng thí nghiệm và phòng thực hành \nKhoa CNTT&TT đến ngày 31/12/2016");
		a.add("Exh.9.3-03");
		a.add("Kế hoạch mua sắm - sửa chữa tài sản \ncủa Khoa CNTT&TT năm 2018");
		a.add("Exh.9.3-04");
		a.add("Quyết định số 243/QĐ-ĐHCT ngày 29/1/2016 \ncủa Hiệu trưởng Trường ĐHCT \nvề việc thành lập các Phòng thí nghiệm \nvà thực hành tại Khoa CNTT&TT");
		a.add("Exh.9.3-05");
		a.add("Thống kê buổi thực hành tại Khoa CNTT&TT 2017-2018");
		a.add("Exh.9.4-01");
		a.add("Thống kê tình hình cơ sở vật chất các phòng thí nghiệm, \nphòng thực hành, phòng chức năng của Khoa CNTT&TT \ntính đến tháng 12/2017");
		a.add("Exh.9.4-02");
		a.add("Trang web http://www.cit.ctu.edu.vn/vpk/login");
		a.add("Exh.9.5-01");
		a.add("Lịch khám sức khỏe \nhttps://tansinhvien.ctu.edu.vn/sinh-hoat/lich-kham-suc-khoe");
		a.add("Exh.9.5-02");
		a.add("Báo cáo tổng kết năm học 2016-2017 \ncủa Khoa CNTT&TT");
		a.add("Exh.9.5-03");
		a.add("Biên bản về việc kiểm tra dụng cụ PCCC \nvà thu hồi, sửa chữa");
		a.add("Exh.10.1-01");
		a.add("Biên bản họp nhóm cải tiến giáo trình Lập trình căn bản \nLần 1");
		a.add("Exh.10.1-02");
		a.add("Tổng hợp phản hồi sinh viên – học phần CT171");
		a.add("Exh.10.1-03");
		a.add("Biên bản sinh hoạt đầu năm học 2018");
		a.add("Exh.10.1-04");
		a.add("Chương trình sự kiên khám phá tri thức 2016");
		a.add("Exh.10.1-05");
		a.add("MOU với VNPT");
		a.add("Exh.10.1-06");
		a.add("MOU với EECS-NCU");
		a.add("Exh.10.1-07");
		a.add("V/v lấy ý kiến phản hồi từ người học \nvề hoạt động giảng dạy của giáo viên \nhọc kỳ II, năm 2017-2018");
		a.add("Exh.10.2-01");
		a.add("Quyết định số 4946-QĐ-ĐHCT \nvề việc thành lập ban chỉ đạo, tổ thư ký điều chỉnh CTĐT (2013)");
		a.add("Exh.10.2-02");
		a.add("Biên bản họp về sửa đổi CTĐT năm 2013");
		a.add("Exh.10.2-03");
		a.add("Biên bản họp về cải tiến chương trình đào tạo \nlần 2 năm 2013");
		a.add("Exh.10.3-01");
		a.add("Biên bản họp nhóm cải tiến giáo trình Lập trình căn bản \nLần 2");
		a.add("Exh.10.3-02");
		a.add("Mẫu luận văn ngành KTPM");
		a.add("Exh.10.3-03");
		a.add("Phiếu chấm luận văn tốt nghiệp đại học ngành KTPM");
		a.add("Exh.10.4-01");
		a.add("Danh sách đề tài sinh viên");
		a.add("Exh.10.4-02");
		a.add("Giấy chứng nhận giải thưởng NCKH sinh viên (2017)");
		a.add("Exh.10.5-01");
		a.add("Báo cáo về phân bổ ngân quỹ cho CICT \ntừ năm 2012 đến ngày 7/2017");
		a.add("Exh.10.5-02");
		a.add("Quyết định phân bổ dự toán ngân sách năm 2018");
		a.add("Exh.10.6-01");
		a.add("Công văn 1276/BGDĐT-NG của Bộ GD-ĐT \nvề việc Hướng dẫn tổ chức lấy ý kiến phản hồi từ người học \nvề hoạt động giảng dạy của giảng viên");
		a.add("Exh.10.6-02");
		a.add("Phiếu lấy ý kiến của sinh viên \nvề hoạt động giảng dạy của giáo viên");
		a.add("Exh.10.6-03");
		a.add("Biên bản Hội nghị viên chức - người lao động \nKhoa CNTT-TT 2017-2018");
		a.add("Exh.10.6-04");
		a.add("Đăng nhập tài khoản đánh giá học phần của giảng viên");
		a.add("Exh.10.6-05");
		a.add("Đăng nhập tài khoản đánh giá học phần \ncủa Trưởng Bộ Môn, Trưởng Khoa");
		a.add("Exh.10.6-06");
		a.add("Biên bản họp bộ môn về việc thực hiện công tác khảo sát \nvà cải tiến học phần Lập trình căn bản");
		a.add("Exh.11.1-01");
		a.add("Kết quả học tập học kỳ 2 năm học 2017-2018 \ncủa một lớp KTPM");
		a.add("Exh.11.1-02");
		a.add("Cam kết của sinh viên bị cảnh báo học vụ và kết quả học tập học kỳ 2 năm học 2016-2017");
		a.add("Exh.11.1-03");
		a.add("Công văn về việc kiểm tra kết quả học tập của sinh viên học kỳ 1 năm 2017-2018");
		a.add("Exh.11.3-01");
		a.add("Báo cáo tình hình việc làm của sinh viên sau 1 năm tốt nghiệp");
		a.add("Exh.11.3-02");
		a.add("Bảng kế hoạch ngày hội việc làm năm 2018");
		a.add("Exh.11.5-01");
		a.add("Phiếu lấy ý kiến sinh viên tốt nghiệp năm 2017");
		a.add("Exh.11.5-02");
		a.add("Phiếu lấy ý kiến của người sử dụng lao động về CTĐT ngành KTPM năm 2018");
		a.add("Exh.11.5-03");
		a.add("Ý kiến phản hồi của sinh viên cho môn học CT171-Nhập môn Công nghệ phần mềm");
		a.add("Exh.11.5-01");
		a.add("Phiếu lấy ý kiến sinh viên tốt nghiệp năm 2017");
		a.add("Exh.11.5-02");
		a.add("Phiếu lấy ý kiến của người sử dụng lao động về CTĐT ngành KTPM năm 2018");
		a.add("Exh.11.5-03");
		a.add("Ý kiến phản hồi của sinh viên cho môn học CT171-Nhập môn Công nghệ phần mềm");

	}
}